### ISSUE TITLE
Phase monitor

### ISSUE THREAD

**Issue by M4tyr0** [YanFett/Wintergatan_data_analysis#26]
Hi,
with the use of multiple microphones spaced 45° apart or an Arduino based rotation sensor on the output, a live comparison based, e.g., on pyaudio would become possible.
This would give Information like the phase against a reference signal or the deviation to the optimal sinus output.

The results can help in identifying different origins of the variation as well as support the “tight” playing via a phase monitor displaying if acceleration or deceleration is required. 

Before I would work on stuff like this, I would like to get an affirmation that it will be used.

Cheers
Dominik

**Comment by YanFett** [comment]
Hi Dominik,

the current scope of this project is to best interpret the results of the data Martin provides.
I will suggest your ideas to Martin, tough i can obviously not promise anything. Its Martin's decision to take.
When/if the experimental setup is modified i would be excited to include your idea in this project, but for now i would suggest not spending your time, energy and motivation on this.

Best wishes
Yan

**Comment by TLMcNulty** [comment]
This is a great idea. It would certainly complicate things but anything that provides another perspective or way to analyze the data can increase confidence/provide another view. 

We don't have any files with such a setup and I don't know if Martin would be willing/interesting in changing his process to provide such a thing.

**Comment by YanFett** [comment]
Martin got back to me and does currently not see a sufficient benefit to warrant the additional experimental setup.
I personally think that the 8 microphones idea is great and will be relevant sooner or later, but for now i will close the issue.
I will get back to you when martin decides to improve his experimental setup!
