### ISSUE TITLE
view not showing correctly

### ISSUE THREAD

**Issue by TheMoen** [YanFett/Wintergatan_data_analysis#40]
You have truly done some good work with this. I however had a issue with the live version.
I confirmed that the height in advanced were making sense, it is at 1333, i also tried width 1080 and height 720. resulting in correct width and incorrect height.

this is what it shows me
![image](https://github.com/YanFett/Wintergatan_data_analysis/assets/116985865/fe23b35b-eac1-4caa-afbd-ad858c45af83)
https://wtg.mcnulty.in/result/c14ffe3b-3fce-4096-bf77-ed087f06091d/TheMoen_Sample1.csv

Issue:
![image](https://github.com/YanFett/Wintergatan_data_analysis/assets/116985865/de1a335d-0bf2-49cd-9a3f-36eda1007149)

**Comment by TLMcNulty** [comment]
Thanks, taking a look now. That height value should never be set to that. Not sure how this happened. Thanks for reporting.

**Comment by TLMcNulty** [comment]
We moved some heights around and it looks like the versions we had that were recreating the problem is fixed. Could you confirm?

**Comment by TheMoen** [comment]
Problem is solved :)
